required = [
  "github.com/golang/mock/mockgen",
  "github.com/mitchellh/gox",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
