required = [
  "github.com/golang/mock/mockgen",
  "github.com/mitchellh/gox",
  "github.com/k0kubun/pp",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"

[[constraint]]
  name = "github.com/creasty/defaults"
  version = "1.2.1"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.2"
